# 서버 설정
server:
  port: 80

# 로깅 설정
logging:
  level:
    org.springframework: INFO
    com.scentquest: DEBUG

spring:
  graphql:
    servlet:
      mapping: /graphql
      enabled: true
    schema:
      location: classpath:graphql/*.graphqls
    cors:
      allowed-origins: http://localhost:3000

  mariadb:
    uri: ENC(yFiNIw+CMtoikuf4ZUSfCX+3ziuWbk8vvC5UeQjmdLFnLbVPtwILHw==)
    database: scent

# Jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 1000